# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0adcfa312b6b71add385dbe51241747b197257c4a044ce11af7e310aebabec2b8107ac3a16b014932bdcc41f1b7a7492e120f3138a6676417ddf550ce695a6fd

test:
  secret_key_base: 4f41b21c592b21129e76ed12a99bbcd4fcf2a5f3d6e4c8654c2fc403ae3b47328317b574fd2ade1dbbb6b8ea8ddd97e74ebe28478180cfad51a931aefe0a8e16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
